id: I42515047
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T20:30:52+00:00'
last_modified: '2022-06-08T02:11:26.448591+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W4PD929
  title: མགུར་ཆུང་མུ་ཏིག་ཕྲེང་བ་དོན་གསལ་ཉམས་ཀྱི་དབྱངས་ཆུང་།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    F011:
      image_group_id: I4PD946
      title: ''
      total_pages: 500
      order: 1
      base_file: F011.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
