id: P004595
initial_creation_type: ocr
created_at: 30/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W4PD929
  title: མགུར་ཆུང་མུ་ཏིག་ཕྲེང་བ་དོན་གསལ་ཉམས་ཀྱི་དབྱངས་ཆུང་།
  author: ''
  volumes:
    004206463dc3423ca663dd3be8c18982:
      image_group_id: I4PD946
      title: ''
      volume_number: 1
      total_pages: 500
      base_file: v001.txt
